### PR TITLE
Ground work and initial version of JAX-RS client filter

### PR DESCRIPTION
**Pull request by phillipross**
Work to support issue https://github.com/joyent/java-http-signature/issues/2

### CODE REVIEW

**Comment by phillipross** [comment]
@dekobon This isn't ready to merge yet, but I just wanted to get a PR filed to allow you to offer early comments on the work.  The maven stuff has been reworked to sync it with patterns and mechanisms used in [java-manta](https://github.com/joyent/java-manta) and an initial version has been implemented, and I've tested it with a separate project, but I still need to pull in some integration test machinery.

Is it possible to get this project also functioning with travis-ci ?

**Comment by dekobon** [comment]
Cool stuff. I will enable Travis for this project. Before we enable CI, we will need to separate out the unit tests and the integration tests again.

**Comment by dekobon** [comment]
I just enabled Travis. It won't run until a .travis.yml file is present.

**Comment by phillipross** [comment]
As far as I can tell... there are no integration tests per se.  There appears to be no test code in the apache httpclient submodule, and the existing test code in the google http-client submodule doesn't actually integrate with google http-client classes.  There is no shading happening either, so I think it's all fine to have the existing tests run during the test phase out of surefire.

I'll still do the separation, though, so that I can have an integration test with jersey client to test the jax-rs client filter, and I'll have that run out of the verify phase via failsafe just like in the [java-manta](https://github.com/joyent/java-manta) project.

We can save the travis config for after all this test machinery is established.

**Comment by phillipross** [comment]
@dekobon This PR is ready for review at this point.

**Comment by dekobon** [comment]
Looks good. Merge whenever you are ready. :+1:

**Pull request merged**
